export const EPS = [
  'Comfamiliar',
  'Nueva Eps',
  'Salud Total',
  'Asmet Salud',
  'Pijaos Salud',
  'Aliansalud',
  'Sanitas',
  'Sura',
  'SOS',
  'Compensar',
  'EPM',
  'Famisanar',
  'Capresoca',
  'Comfachocó',
  'EPS Familiar de Colombia',
  'Emssanar',
  'Capital Salud',
  'Savia Salud',
];
